package Threads_ConcurrencyThreads.ExecutorsThreadPool.NewFixedThreadPool;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.*;

public class ReportGenerator implements Callable<String>{
    private final String reportName;

    public ReportGenerator(String reportName) {
        this.reportName = reportName;
    }

    @Override
    public String call() throws Exception {
        int sleepTime = ThreadLocalRandom.current().nextInt(800);
        Thread.sleep(sleepTime);
        LocalTime before = LocalTime.now();
        System.out.println("\nWaiting at: " + before + "\n");
        return reportName + " generated by " + Thread.currentThread().getName();
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException, TimeoutException {
        ExecutorService service = Executors.newFixedThreadPool(3);
        List<Future<String>> futureList = new ArrayList<>();

        for (int i = 0; i < 9; i++) {
            futureList.add(service.submit(new ReportGenerator("report-" + i)));
        }

        for (Future<String> future : futureList) {
            LocalTime before = LocalTime.now();
            System.out.println("\nWaiting at: " + before + "\n");
            System.out.println(future.get(2, TimeUnit.SECONDS));
            LocalTime after = LocalTime.now();
            System.out.println("\nGot result at: " + after);
        }

        service.shutdown();
    }
}